import argparse
import os
import time
import shutil
from PIL import Image, ImageEnhance

def run_mock_generation(input_path, mask_path, output_path, prompt):
    print("Running in MOCK MODE...")
    time.sleep(2.0)  # Simulate generation delay
    
    if not os.path.exists(input_path):
        print(f"Error: Input path {input_path} does not exist")
        return False
        
    try:
        # Create output directory if it doesn't exist
        if os.path.dirname(output_path):
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
        img = Image.open(input_path)
        # Create a visually enhanced mock photo to simulate professional editing
        enhancer = ImageEnhance.Color(img)
        img_enhanced = enhancer.enhance(1.25)  # Make colors slightly more vibrant
        
        enhancer_brightness = ImageEnhance.Brightness(img_enhanced)
        img_bright = enhancer_brightness.enhance(1.05)  # Make it slightly brighter
        
        # Save output
        img_bright.save(output_path, format="JPEG")
        print(f"Mock generated image saved to {output_path}")
        return True
    except Exception as e:
        print(f"Error in mock generation: {e}")
        return False

def run_real_generation(args):
    # Imports inside to avoid loading overhead in mock mode
    try:
        from google import genai
        from google.genai import types
    except ImportError:
        print("Error: The 'google-genai' package is not installed in this Python environment.")
        return False
        
    print(f"Initializing Google GenAI Client (Model: {args.model})...")
    
    try:
        # Initialize client
        if args.vertex_ai:
            if not args.project:
                print("Error: GCP Project ID is required for Vertex AI mode (--project)")
                return False
            client = genai.Client(
                vertexai=True,
                project=args.project,
                location=args.location or "us-central1"
            )
        else:
            api_key = args.api_key or os.environ.get("GEMINI_API_KEY")
            if not api_key:
                print("Error: Gemini API Key is required (pass --api_key or set GEMINI_API_KEY)")
                return False
            client = genai.Client(api_key=api_key)
            
        # Create output directory if it doesn't exist
        if os.path.dirname(args.output):
            os.makedirs(os.path.dirname(args.output), exist_ok=True)
            
        print(f"Loading base image: {args.image}")
        base_img = types.Image.from_file(location=args.image)
        
        print(f"Loading mask image: {args.mask}")
        mask_img = types.Image.from_file(location=args.mask)
        
        # Call inpainting
        print("Executing inpainting request...")
        raw_ref = types.RawReferenceImage(
            reference_id=1,
            reference_image=base_img
        )
        mask_ref = types.MaskReferenceImage(
            reference_id=2,
            reference_image=mask_img,
            config=types.MaskReferenceConfig(mask_mode="MASK_MODE_USER_PROVIDED")
        )
        
        config = types.EditImageConfig(
            edit_mode="EDIT_MODE_INPAINT_INSERTION",
            number_of_images=1,
            output_mime_type="image/jpeg"
        )
        if args.seed is not None:
            config.seed = int(args.seed)
            
        response = client.models.edit_image(
            model=args.model,
            prompt=args.prompt,
            reference_images=[raw_ref, mask_ref],
            config=config
        )
        
        if response.generated_images:
            response.generated_images[0].image.save(args.output)
            print(f"Generated image saved to {args.output}")
            return True
        else:
            print("Error: No images were generated by the API.")
            return False
            
    except Exception as e:
        print(f"Error in real generation: {e}")
        return False

def main():
    parser = argparse.ArgumentParser(description="Generate catalog image via Google GenAI API")
    parser.add_argument("--image", required=True, help="Path to input raw photo")
    parser.add_argument("--mask", required=True, help="Path to mask image")
    parser.add_argument("--output", required=True, help="Path to save output generated photo")
    parser.add_argument("--prompt", required=True, help="Engineering prompt for model and background")
    parser.add_argument("--style", default="clean", help="Style key (clean, festive, bridal)")
    parser.add_argument("--seed", type=int, default=None, help="Fixed random seed")
    parser.add_argument("--api_key", default=None, help="Gemini API Key")
    parser.add_argument("--vertex_ai", action="store_true", help="Use Vertex AI mode")
    parser.add_argument("--project", default=None, help="GCP Project ID")
    parser.add_argument("--location", default="us-central1", help="GCP Location")
    parser.add_argument("--model", default="imagen-3.0-capability-001", help="Model name")
    parser.add_argument("--mock", action="store_true", help="Run in mock mode (no API calls)")
    
    args = parser.parse_args()
    
    if args.mock:
        success = run_mock_generation(args.image, args.mask, args.output, args.prompt)
    else:
        success = run_real_generation(args)
        
    if success:
        print("SUCCESS")
    else:
        print("FAILED")
        import sys
        sys.exit(1)

if __name__ == "__main__":
    main()
